// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecoleccionResiduosApi.Data;

#nullable disable

namespace RecoleccionResiduosApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("RecoleccionResiduosApi.Models.Recoleccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsValida")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<double?>("PesoKg")
                        .HasColumnType("REAL");

                    b.Property<int>("PuntosGanados")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subtipo")
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoResiduoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TipoResiduoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Recolecciones");
                });

            modelBuilder.Entity("RecoleccionResiduosApi.Models.TipoResiduo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Puntos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TiposResiduo");
                });

            modelBuilder.Entity("RecoleccionResiduosApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Puntos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("RecoleccionResiduosApi.Models.Recoleccion", b =>
                {
                    b.HasOne("RecoleccionResiduosApi.Models.TipoResiduo", "TipoResiduo")
                        .WithMany("Recolecciones")
                        .HasForeignKey("TipoResiduoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecoleccionResiduosApi.Models.Usuario", "Usuario")
                        .WithMany("Recolecciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoResiduo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RecoleccionResiduosApi.Models.TipoResiduo", b =>
                {
                    b.Navigation("Recolecciones");
                });

            modelBuilder.Entity("RecoleccionResiduosApi.Models.Usuario", b =>
                {
                    b.Navigation("Recolecciones");
                });
#pragma warning restore 612, 618
        }
    }
}
